Fixed a crash that happens if you haven't saved any WiFi networks in the system, when you open the configuration screen for WiFi networks in settings
Error Log:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.matoski.adbm/com.matoski.adbm.activity.WiFiListViewCheckboxesActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2060)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2085)
at android.app.ActivityThread.access$600(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4747)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.matoski.adbm.activity.WiFiListViewCheckboxesActivity.prepareAdapter(WiFiListViewCheckboxesActivity.java:143)
at com.matoski.adbm.activity.WiFiListViewCheckboxesActivity.onCreate(WiFiListViewCheckboxesActivity.java:101)
at android.app.Activity.performCreate(Activity.java:5008)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2024)
... 11 more